# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G6P1qtwtWnqb3IHJ0qd71OtyRlGECtA
"""

print("Nama: Fadhli Kamil Maulana")
print("NIM: 1301170262")